#########################################################################
# SpigotPing by xDefcon - Configuration file
# https://www.spigotmc.org/resources/spigotping.24419/
# Please check for updates, and remember to update the config if needed!
#########################################################################

# Section releated to /ping command.
ping-command:
  # Customize the output of the command, use %ping% to indicate player's latency.
  ping-message: "&a[Ping] &7Your ping is: &a%ping%ms"

# Section releated to the per command permission system.
permission-system:
  # Set this to true if you want to enable the permission system.
  enabled: false
  # Customize the message sent to the players if they do not have required permission.
  no-perm-message: "&cYou do not have permissions to execute this command."

# Section releated to the per command permission system.
sound-manager:
  # Set this to true if you want to enable sound after the ping command.
  enabled: true
  # Choose the sound type. A list of all available sounds is retrievable here: http://bit.ly/bukkit-sounds
  # WARNING: The link provided is a Sound list for 1.11.2, if you are using other versions, do a quick search for
  # specific sounds, search something like "Bukkit 1.8 Sound Enum".
  # EXAMPLE: NOTE_PLING will work in versions below 1.9, for 1.9 and greater you should use BLOCK_NOTE_PLING
  sound-type: "NOTE_PLING"
  # Customize the volume (min: 0.0 - max: 1.0)
  volume: 1.0
  # Customize the pitch (playing speed, 1.0 = normal speed, 0.5 = half speed)
  pitch: 1.0

# Section releated to the tablist management (you can open the tablist by pressing TAB in game).
tablist:
  # Set this to true if you want to show player's ping in the tablist.
  enabled: true
  # Customize the tablist prefix, use %ping% to indicate player's latency. You do not need to put a space at the end. Set this to "" to disable.
  prefix: "&7[&a%ping%ms&7]"
  # Customize the tablist suffix, use %ping% to indicate player's latency. Set this to "" to disable.
  suffix: ""
  # Update delay time (in seconds) - 5 means that the tablist is updated every 5 seconds.
  update-delay: 5